/******************************************************************************
*
*  Status.java
*     QuoddMsg._mt    == 'x' (MsgTypes._mtDEAD)
*     QuoddMsg._mtSub == <Any>
*
*     class Status : public QuoddMsg
*     {
*     public:
*        u_char _reserved[4];
*        u_char _text[64];
*     };
*
*  REVISION HISTORY:
*      8 DEC 2011 jcs  Created.
*     22 FEB 2012 jcs  Build  14: v0.12: Copy constructor
*      9 OCT 2012 jcs  Build  40: v0.12: Copy super() - DUH!!; SetTkr()
*      3 JUN 2014 jcs  Build  77: v0.24: ( Ticker, StsMsg ) constructor 
*      2 OCT 2014 jcs  Build  83: v0.24: _tHbeat; _errIO
*     23 JUN 2015 jcs  Build  94: v0.25: Dump()
*      1 APR 2016 jcs  Build 100: v0.25: _tHbeat > 0x7f
*  
*  (c) 1994-2016 Gatea Ltd.
*******************************************************************************/
package QuoddFeed.msg;

import java.util.*;
import QuoddFeed.msg.*;
import QuoddFeed.util.*;


/////////////////////////////////////////////////////////////////
//
//                  c l a s s    S t a t u s
//
/////////////////////////////////////////////////////////////////
/**
 * The Status class is a parsed status message from UltraCache
 * <p>
 * A Status is generated by the {@link QuoddFeed.util.UltraChan} class
 * which invokes the
 * {@link QuoddFeed.util.UltraChan#OnStatus(String,Status)}
 * callback method to deliver the update into your application.
 */
public class Status extends QuoddMsg
{
   static public int MINSZ = QuoddMsg.MINSZ + 68;

   private char   _tHbeat;
   private char   _errIO;
   private char   _resv3;
   private char   _resv4;
   private String _text;
   private String _stsTkr;  // Override private QuoddMsg._tkr

   ///////////////////////////////
   // Constructor
   ///////////////////////////////
   public Status()
   {
      _tHbeat = 0;
      _errIO  = 0;  // IOException
      _resv3  = 0;
      _resv4  = 0;
      _text   = "";
      _stsTkr = null;
   }

   public Status( String tkr, String text )
   {
      byte[] b = new byte[] { 0x00, QuoddMsg.MINSZ,     // QuoddMsg._len
                             (byte)_mtDEAD,             // QuoddMsg._mt
                             0x00,                      // QuoddMsg._mtSub
                             0x00,                      // QuoddMsg._protocol
                             0x00,                      // QuoddMsg._chanIdx
                             0x00, 0x00, 0x00, 0x00,    // QuoddMsg._time
                             0x00, 0x00, 0x00, 0x00,    // QuoddMsg._tag
                             0x00, 0x00, 0x00, 0x00  }; // QuoddMsg._RTL

      super.Set( b, 0, QuoddMsg.MINSZ );
      _tHbeat = 0;
      _errIO  = 0;
      _resv3  = 0;
      _resv4  = 0;
      _text   = text;
      _stsTkr = tkr;
      SetTkr( tkr );
   }

   public Status( byte[] b, int off, int nLeft )
   {
      this.Set( b, off, nLeft );
   }

   public Status( Status c )
   {
      super( c );
      _tHbeat = c._tHbeat;
      _errIO  = c._errIO;
      _resv3  = c._resv3;
      _resv4  = c._resv4;
      _text   = new String( c._text );
      _stsTkr = ( c._stsTkr != null ) ? new String( c._stsTkr ) : null;
   }

   public Status clone() { return new Status( this ); }


   ///////////////////////////////
   // Access / Operations
   ///////////////////////////////
   /**
    * Text
    */
   public String Text()
   {
      return _text;
   }

   /**
    * Heartbeat Interval (seconds)
    */
   public int HeartbeatInterval()
   {
      return _tHbeat;
   }

   /**
    * true if this Status due to IOException
    */
   public boolean IsIOException()
   {
      return( _errIO == 1 );
   }

   /**
    * Override
    */
   public String tkr()
   {
      return ( _stsTkr != null ) ? _stsTkr : super.tkr();
   }

   public void SetTkr( String tkr )
   {
      _stsTkr = new String( tkr );
   }


   ///////////////////////////////
   // QuoddMsg Override - Dump 
   ///////////////////////////////
   @Override
   public String pMsgName()
   {
      return super.pMsgName() + "-DEAD";
   }

   @Override
   public String Dump()
   {
      String s;

      s  = super.Dump();
      s += s.format( "%s\n", Text() );
      return s;
   }


   ///////////////////////////////
   // Mutator
   ///////////////////////////////
   @Override
   public QuoddMsg Set( byte[] b, int off, int nLeft )
   {
      String err;

      _stsTkr = null;
      super.Set( b, off, nLeft );
      off += QuoddMsg.MINSZ;
      try {
         _tHbeat  = (char)b[off+0];
         _tHbeat &= 0x00ff; 
         _errIO   = (char)b[off+1];
         _resv3   = (char)b[off+2];
         _resv4   = (char)b[off+3];
         _text    = new String( b, off+4,64 ).trim();

      } catch( StringIndexOutOfBoundsException e ) {
         err = e.getMessage();
      }
      return this;
   }

   /**
    * Flags this Status message as due to IOException rather than
    * anything from UltraCache (i.e., non-existent item).
    */
   public void SetIOException()
   {
      _errIO = 1;
   }
}
