name: computils

on:
  push:
    branches: [ gradle-computil ]

jobs:
  build:
    name: Compile Build
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory:  ./CompressionCode/

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
       
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build