
name: computils

on:
  push:
    branches: [ gradle-computil ]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}