/******************************************************************************
*
*  EQQuoteMM.java
*     QuoddMsg._mt    == 'e' (_mtEQUITY)
*     QuoddMsg._mtSub == '+' (_eqSubQTESHORTMM) -or-
*     QuoddMsg._mtSub == ',' (_eqSubQTELONGMM)
*
*     class EQQteShortMM : public QuoddMsg
*     {
*     public:
*        u_char _bidPrc[4];
*        u_char _askPrc[4];
*        u_char _bidSize;
*        u_char _askSize;
*        u_char _mktCtrLocCode[2];
*        u_char _mmidLocCode[2];
*        u_char _qteCond;
*        u_char _qteFlags[2];
*        u_char _mktCtr[4];
*        u_char _mmid[4];
*     };
*
*     class EQQteLongMM : public QuoddMsg
*     {
*     public:
*        // Same; Prices are 8 bytes; Sizes are 4 bytes
*     };
*
*  REVISION HISTORY:
*     18 DEC 2011 jcs  Created.
*     22 FEB 2012 jcs  Build 14: v0.12: Copy constructor
*     17 SEP 2012 jcs  Build 37: v0.24: IsOpen()
*     15 JUN 2013 jcs  Build 64: v0.24: CanDisplayBid() / CanDisplayAsk()
*     23 JUN 2015 jcs  Build 94: v0.25: Dump()
*  
*  (c) 1994-2015 Gatea Ltd.
*******************************************************************************/
package QuoddFeed.msg;

import java.util.*;
import QuoddFeed.msg.*;
import QuoddFeed.util.*;

/////////////////////////////////////////////////////////////////
//
//                c l a s s   E Q Q u o t e M M
//
/////////////////////////////////////////////////////////////////
/**
 * The EQQuoteMM class is a parsed Short- or Long-Form Quote Market Maker
 * message received from the UltraCache.
 * <p>
 * A EQQuoteMM is generated by the {@link QuoddFeed.util.UltraChan} class
 * which invokes the
 * {@link QuoddFeed.util.UltraChan#OnUpdate(String,EQQuoteMM)}
 * callback method to deliver the update into your application.
 */
public class EQQuoteMM extends QuoddMsg
{
   static public int SHORTSZ = QuoddMsg.MINSZ + 25;
   static public int LONGSZ  = QuoddMsg.MINSZ + 39;

   public  double _bid;
   public  long   _bidSize;
   public  double _ask;
   public  long   _askSize;
   private int    _iMktCtr;
   private int    _iMmid;
   public  char   _qteCond;
   public  int    _qteFlags;
   public  String _mktCtr;
   public  String _mmid;

   ///////////////////////////////
   // Constructor
   ///////////////////////////////
   public EQQuoteMM()
   {
      _bid      = 0.0;
      _bidSize  = 0;
      _ask      = 0.0;
      _askSize  = 0;
      _iMktCtr  = 0;
      _iMmid    = 0;
      _qteCond  = '?';
      _qteFlags = 0;
      _mktCtr   = "";
      _mmid     = "";
   }

   public EQQuoteMM( byte[] b, int off, int nLeft )
   {  
      this.Set( b, off, nLeft );
   }  

   public EQQuoteMM( EQQuoteMM c )
   {
      super( c );
      _bid      = c._bid;
      _bidSize  = c._bidSize;
      _ask      = c._ask;
      _askSize  = c._askSize;
      _iMktCtr  = c._iMktCtr;
      _iMmid    = c._iMmid;
      _qteCond  = c._qteCond;
      _qteFlags = c._qteFlags;
      _mktCtr   = new String( c._mktCtr );
      _mmid     = new String( c._mmid );
   }

   public EQQuoteMM clone() { return new EQQuoteMM( this ); }


   ///////////////////////////////
   // Access
   ///////////////////////////////
   /**
    * Returns true if this quote is open
    * <p>
    * @return True if this quote is open
    */
   public boolean IsOpen()
   {
      return QuoddFeed.Enum.EquitySpec.IsOpen( this );
   }

   /**
    * Returns true if this quote contains displayable bid
    * <p>
    * @return True if this quote contains displayable bid
    */
   public boolean CanDisplayBid()
   {
      return QuoddFeed.Enum.EquitySpec.CanDisplayBid( this );
   }

   /**
    * Returns true if this quote contains displayable ask
    * <p>
    * @return True if this quote contains displayable ask
    */
   public boolean CanDisplayAsk()
   {
      return QuoddFeed.Enum.EquitySpec.CanDisplayAsk( this );
   }


   ///////////////////////////////
   // QuoddMsg Override - Dump 
   ///////////////////////////////
   @Override
   public String Dump()
   {
      String s;

      s  = super.Dump();
      s += s.format( "{%s,%s} %8.4f x %8.4f; %dx%d; 0x%02x\n",
            _mmid, _mktCtr, _bid, _ask, _bidSize, _askSize, _qteFlags );
      return s;
   }


   ///////////////////////////////
   // Mutator
   ///////////////////////////////
   @Override
   public QuoddMsg Set( byte[] b, int off, int nLeft )
   {
      QuoddMsg rtn;

      super.Set( b, off, nLeft );
      switch( mtSub() ) {
         case _eqSubQTESHORTMM:
            return SetShort( b, off, nLeft );
         case _eqSubQTELONGMM:
            return SetLong( b, off, nLeft );
      }
      return null;
   }



   ///////////////////////////////
   // Helpers
   ///////////////////////////////
   /**
    * Parse the short-form EQQuoteMM message from the incoming byte buffer.
    * <p>
    * @param b Input buffer
    * @param off Offset in b
    * @param nLeft NumBytes remaining in Input byte[] array after offset.
    * @return this
    */
   private QuoddMsg SetShort( byte[] b, int off, int nLeft )
   {
      String err;

      off += QuoddMsg.MINSZ;
      try {
         _bid      = BigEndian.GetPrc32( b, off+ 0 );
         _ask      = BigEndian.GetPrc32( b, off+ 4 );
         _bidSize  = BigEndian.GetInt8( b, off+ 8 );
         _askSize  = BigEndian.GetInt8( b, off+ 9 );
         _iMktCtr  = BigEndian.GetInt16( b, off+10 );
         _iMmid    = BigEndian.GetInt16( b, off+12 );
         _qteCond  = (char)b[off+14];
         _qteFlags = BigEndian.GetInt16( b, off+15 );
         _mktCtr   = new String( b, off+17, 4 ).trim();
         _mmid     = new String( b, off+21, 4 ).trim();
      } catch( StringIndexOutOfBoundsException e ) {
         err = e.getMessage();
      }
      return this;
   }

   /**
    * Parse the long-form EQQuoteMM message from the incoming byte buffer.
    * <p>
    * @param b Input buffer
    * @param off Offset in b
    * @param nLeft NumBytes remaining in Input byte[] array after offset.
    * @return this
    */
   private QuoddMsg SetLong( byte[] b, int off, int nLeft )
   {
      String err;

      off += QuoddMsg.MINSZ;
      try {
         _bid      = BigEndian.GetPrc64( b, off+ 0 );
         _ask      = BigEndian.GetPrc64( b, off+ 8 );
         _bidSize  = BigEndian.GetInt32( b, off+16 );
         _askSize  = BigEndian.GetInt32( b, off+20 );
         _iMktCtr  = BigEndian.GetInt16( b, off+24 );
         _iMmid    = BigEndian.GetInt16( b, off+26 );
         _qteCond  = (char)b[off+28];
         _qteFlags = BigEndian.GetInt16( b, off+29 );
         _mktCtr   = new String( b, off+31, 4 ).trim();
         _mmid     = new String( b, off+35, 4 ).trim();
      } catch( StringIndexOutOfBoundsException e ) {
         err = e.getMessage();
      }
      return this;
   }
}
