/******************************************************************************
*
*  EQQuote.java
*     QuoddMsg._mt    == 'e'  (_mtEQUITY)
*     QuoddMsg._mtSub == '\'' (_eqSubQTESHORT) -or-
*     QuoddMsg._mtSub == '('  (_eqSubQTELONG)
*
*     class EQQteShort : public QuoddMsg
*     {
*     public:
*        u_char _bidPrc[4];
*        u_char _askPrc[4];
*        u_char _bidSize;
*        u_char _askSize;
*        u_char _mktCtrLocCode[2];
*        u_char _qteCond;
*        u_char _qteFlags[2];
*        u_char _mktCtr[4];
*     };
*
*     class EQQteLong : public QuoddMsg
*     {
*     public:
*        // Same; Prices are 8 bytes; Sizes are 4 bytes
*     };
*
*  REVISION HISTORY:
*      9 NOV 2011 jcs  Created.
*     22 FEB 2012 jcs  Build 14: v0.12: Copy constructor
*     30 MAY 2012 jcs  Build 21: v0.19: SetLong() _mktCtr - wrong offset
*     20 JUL 2012 jcs  Build 29: v0.22: IsOneSided()
*     23 JUN 2015 jcs  Build 94: v0.25: Dump()
*  
*  (c) 1994-2015 Gatea Ltd.
*******************************************************************************/
package QuoddFeed.msg;

import java.util.*;
import QuoddFeed.Enum.*;
import QuoddFeed.msg.*;
import QuoddFeed.util.*;

/////////////////////////////////////////////////////////////////
//
//                c l a s s   E Q Q u o t e
//
/////////////////////////////////////////////////////////////////
/**
 * The EQQuote class is a parsed Short- or Long-Form Quote message received 
 * from the UltraCache.
 * <p>
 * A EQQuote is generated by the {@link QuoddFeed.util.UltraChan} class
 * which invokes the
 * {@link QuoddFeed.util.UltraChan#OnUpdate(String,EQQuote)}
 * callback method to deliver the update into your application.
 */
public class EQQuote extends QuoddMsg
{
   static public int SHORTSZ = QuoddMsg.MINSZ + 19;
   static public int LONGSZ  = QuoddMsg.MINSZ + 33;

   public  double _bid;
   public  long   _bidSize;
   public  double _ask;
   public  long   _askSize;
   private int    _iMktCtr;
   public  char   _qteCond;
   public  int    _qteFlags;
   public  String _mktCtr;

   ///////////////////////////////
   // Constructor
   ///////////////////////////////
   public EQQuote()
   {
      _bid      = 0.0;
      _bidSize  = 0;
      _ask      = 0.0;
      _askSize  = 0;
      _iMktCtr  = 0;
      _qteCond  = '?';
      _qteFlags = 0;
      _mktCtr   = "";
   }

   public EQQuote( byte[] b, int off, int nLeft )
   {
      this.Set( b, off, nLeft );
   }

   public EQQuote( EQQuote c )
   {
      super( c );
      _bid      = c._bid;
      _bidSize  = c._bidSize;
      _ask      = c._ask;
      _askSize  = c._askSize;
      _iMktCtr  = c._iMktCtr;
      _qteCond  = c._qteCond;
      _qteFlags = c._qteFlags;
      _mktCtr   = new String( c._mktCtr );
   }

   public EQQuote clone() { return new EQQuote( this ); }


   ///////////////////////////////
   // Access
   ///////////////////////////////
   /**
    * Returns true if this is a one-sided quote
    * <p>
    * @return true if this is a one-sided quote
    */
   public boolean IsOneSided()
   {
      return EquitySpec.IsOneSided( this );
   }

   /**
    * Returns true if this is a one-sided quote missing the BID.  In this case 
    * the BID is supplied out of the cache.
    * <p>
    * @return true if this is a one-sided quote missing the BID.  In this case
    * the BID is supplied out of the cache.
    */
   public boolean IsCachedBid() 
   {
      return EquitySpec.IsCachedBid( this );
   }

   /**
    * Returns true if this is a one-sided quote missing the ASK.  In this case
    * the ASK is supplied out of the cache.
    * <p>
    * @return true if this is a one-sided quote missing the ASK.  In this case 
    * the ASK is supplied out of the cache.
    */
   public boolean IsCachedAsk()
   {
      return EquitySpec.IsCachedAsk( this );
   }


   ///////////////////////////////
   // QuoddMsg Override - Dump 
   ///////////////////////////////
   @Override
   public String Dump()
   {
      String s;

      s  = super.Dump();
      s += s.format( "{%s} %8.4f x %8.4f; %dx%d\n",
         _mktCtr, _bid, _ask, _bidSize, _askSize );
      return s;
   }


   ///////////////////////////////
   // Mutator
   ///////////////////////////////
   @Override
   public QuoddMsg Set( byte[] b, int off, int nLeft )
   {
      QuoddMsg rtn;

      super.Set( b, off, nLeft );
      switch( mtSub() ) {
         case _eqSubQTESHORT:
            return SetShort( b, off, nLeft );
         case _eqSubQTELONG:
            return SetLong( b, off, nLeft );
      }
      return null;
   }



   ///////////////////////////////
   // Helpers
   ///////////////////////////////
   /**
    * Parse the short-form EQQuote message from the incoming byte buffer.
    * <p>
    * @param b Input buffer
    * @param off Offset in b
    * @param nLeft NumBytes remaining in Input byte[] array after offset.
    * @return this
    */
   private QuoddMsg SetShort( byte[] b, int off, int nLeft )
   {
      String err;

      off += QuoddMsg.MINSZ;
      try {
         _bid      = BigEndian.GetPrc32( b, off+ 0 );
         _ask      = BigEndian.GetPrc32( b, off+ 4 );
         _bidSize  = BigEndian.GetInt8( b, off+ 8 );
         _askSize  = BigEndian.GetInt8( b, off+ 9 );
         _iMktCtr  = BigEndian.GetInt16( b, off+10 );
         _qteCond  = (char)b[off+12];
         _qteFlags = BigEndian.GetInt16( b, off+13 );
         _mktCtr   = new String( b, off+15, 4 ).trim();
      } catch( StringIndexOutOfBoundsException e ) {
         err = e.getMessage();
      }
      return this;
   }

   /**
    * Parse the long-form EQQuote message from the incoming byte buffer.
    * <p>
    * @param b Input buffer
    * @param off Offset in b
    * @param nLeft NumBytes remaining in Input byte[] array after offset.
    * @return this
    */
   private QuoddMsg SetLong( byte[] b, int off, int nLeft )
   {
      String err;

      off += QuoddMsg.MINSZ;
      try {
         _bid      = BigEndian.GetPrc64( b, off+ 0 );
         _ask      = BigEndian.GetPrc64( b, off+ 8 );
         _bidSize  = BigEndian.GetInt32( b, off+16 );
         _askSize  = BigEndian.GetInt32( b, off+20 );
         _iMktCtr  = BigEndian.GetInt16( b, off+24 );
         _qteCond  = (char)b[off+26];
         _qteFlags = BigEndian.GetInt16( b, off+27 );
         _mktCtr   = new String( b, off+29, 4 ).trim();
      } catch( StringIndexOutOfBoundsException e ) {
         err = e.getMessage();
      }
      return this;
   }
}
