name: EquityCPD

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory:  ./EquityCPD/

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
       
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - uses: actions/download-artifact@v3
      with:
#         name: my-artifact
        path: ./build/distributions/EquityCPD-1.0.tar
    
#     - name: Display structure of downloaded files
#       run: ls -R
